/* AUTHENTICATION */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* DRAMA */
export const DRAMA_ADD = "DRAMA_ADD";
export const DRAMA_ADD_SUCCESS = "DRAMA_ADD_SUCCESS"
export const DRAMA_ADD_FAILURE = "DRAMA_ADD_FAILURE"

/* DRAMA LIST */
export const DRAMA_LIST = "DRAMA_LIST";
export const DRAMA_LIST_SUCCESS = "DRAMA_LIST_SUCCESS";
export const DRAMA_LIST_FAILURE = "DRAMA_LIST_FAILURE";

/* DRAMA REMOVE */
export const DRAMA_REMOVE = "DRAMA_REMOVE";
export const DRAMA_REMOVE_SUCCESS = "DRAMA_REMOVE_SUCCESS";
export const DRAMA_REMOVE_FAILURE = "DRAMA_REMOVE_FAILURE";


/* ERROR */
export const ERROR_ADD = "ERROR_ADD";
export const ERROR_ADD_SUCCESS = "ERROR_ADD_SUCCESS";
export const ERROR_ADD_FAILURE = "ERROR_ADD_FAILURE";

/* ERROR LIST */
export const ERROR_LIST = "ERROR_LIST";
export const ERROR_LIST_SUCCESS = "ERROR_LIST_SUCCESS";
export const ERROR_LIST_FAILURE = "ERROR_LIST_FAILURE";

/* ERROR REPORT REMOVE */
export const ERROR_REMOVE = "ERROR_REMOVE";
export const ERROR_REMOVE_SUCCESS = "ERROR_REMOVE_SUCCESS";
export const ERROR_REMOVE_FAILURE = "ERROR_REMOVE_FAILURE";

/* NEW DRAMA LIST */
export const NEW_DRAMA_LIST = "NEW_DRAMA_LIST";
export const NEW_DRAMA_LIST_SUCCESS = "NEW_DRAMA_LIST_SUCCESS";
export const NEW_DRAMA_LIST_FAILURE = "NEW_DRAMA_LIST_FAILURE";

/* DRAMA COUNT */
export const DRAMA_COUNT = "DRAMA_COUNT";
export const DRAMA_COUNT_SUCCESS = "DRAMA_COUNT_SUCCESS";
export const DRAMA_COUNT_FAILURE = "DRAMA_COUNT_FAILURE";
