/* AUTHENTICATION */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* DRAMA */
export const DRAMA_ADD = "DRAMA_ADD";
export const DRAMA_ADD_SUCCESS = "DRAMA_ADD_SUCCESS"
export const DRAMA_ADD_FAILURE = "DRAMA_ADD_FAILURE"

/* DRAMA LIST */
export const DRAMA_LIST = "DRAMA_LIST";
export const DRAMA_LIST_SUCCESS = "DRAMA_LIST_SUCCESS";
export const DRAMA_LIST_FAILURE = "DRAMA_LIST_FAILURE";
